apiVersion: apps/v1
kind: apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
spec:
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
      - name: nodeapp
        image: jacobciodyk/nodeapp:latest
        ports:
        - containerPort: 3000
---

apiVersion: v1
kind: apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
spec:
  selector:
    app: myapp
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3000
    nodePort: 31110





